# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7cda17f724822d008f1214140a6ee1b8"
application_url = "https://happens-car-garcia-dont.trycloudflare.com"
embedded = true
name = "RecoSys"
handle = "recosys-2"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://happens-car-garcia-dont.trycloudflare.com/auth/callback",
  "https://happens-car-garcia-dont.trycloudflare.com/auth/shopify/callback",
  "https://happens-car-garcia-dont.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "recosysdev.myshopify.com"
automatically_update_urls_on_dev = true
